#!/bin/bash -xe
#
# Build for multiple platforms
#

platforms=(amd64 arm64 arm)

IFS='/'
read -r DOCKER_HUB DOCKER_ORG DOCKER_IMAGE <<< "${DOCKER_REPO}"

MANIFEST=${DOCKER_ORG}/${DOCKER_IMAGE}:${DOCKER_TAG}



# remove any previous builds
rm -Rf target/*.tar
mkdir -p target

# generate image for each platform
for platform in "${platforms[@]}"; do
    docker run --rm --privileged -v ${PWD}:/tmp/work --entrypoint buildctl-daemonless.sh moby/buildkit:master \
           build \
           --frontend dockerfile.v0 \
           --opt platform=linux/${platform} \
           --opt filename=${DOCKERFILE_PATH} \
           --opt build-arg:GIT_BRANCH=${SOURCE_BRANCH} \
           --opt build-arg:GIT_COMMIT_ID=${SOURCE_COMMIT} \
           --output type=docker,name=${MANIFEST}-${platform},dest=/tmp/work/target/${DOCKER_IMAGE}-${platform}.docker.tar \
           --local context=/tmp/work \
           --local dockerfile=/tmp/work \
           --progress plain

done

# load all generated images
for platform in "${platforms[@]}"; do
    docker load --input ./target/${DOCKER_IMAGE}-${platform}.docker.tar
done
