#!/bin/bash -xe
#
# Downloads a local copy of qemu on docker-hub build machines
#

for arch in aarch64 arm; do
    curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-${arch}.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-${arch}/qemu-arm-static .
done
